import type { HomeAssistant } from "./hass";

type Path = (string | number)[];

export class SaveError extends Error {}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Home Assistant rejects websocket calls with a plain { code, message } object, not an Error.
function reason(err: unknown): string {
  return String((err as { message?: unknown })?.message ?? err).replace(/\.$/, "");
}

/** JSON with object keys sorted, so two configs compare equal whatever order their keys were written in. */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) =>
    isObject(v) ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) : v,
  );
}

/** Paths to every card in a dashboard config equal to `card`, looking inside views, sections and stacks alike. */
export function findCard(dashboard: unknown, card: Record<string, unknown>): Path[] {
  const target = canonical(card);
  const found: Path[] = [];
  const walk = (node: unknown, path: Path): void => {
    if (Array.isArray(node)) node.forEach((child, i) => walk(child, [...path, i]));
    else if (isObject(node)) {
      if (node.type === card.type && canonical(node) === target) found.push(path);
      else for (const [key, child] of Object.entries(node)) walk(child, [...path, key]);
    }
  };
  walk(dashboard, []);
  return found;
}

/** A copy of `node` with the value at `path` swapped for `value`. */
export function replaceAt(node: unknown, path: Path, value: unknown): unknown {
  if (path.length === 0) return value;
  const [key, ...rest] = path;
  if (Array.isArray(node)) return node.map((child, i) => (i === key ? replaceAt(child, rest, value) : child));
  const record = node as Record<string, unknown>;
  return { ...record, [key]: replaceAt(record[key], rest, value) };
}

/** The dashboard a page belongs to, as the websocket API names it: null for the default one at /lovelace. */
export function dashboardUrlPath(pathname: string): string | null {
  const first = pathname.split("/")[1] ?? "";
  return first === "" || first === "lovelace" ? null : first;
}

/** The part of a dashboard page's URL that names its view, empty for the first view. */
export function viewPath(pathname: string): string {
  return pathname.split("/")[2] ?? "";
}

/** The index of the view HA shows for `view`, which it reads as a view's path first and its index second. */
export function viewIndex(dashboard: unknown, view: string): number {
  const views = isObject(dashboard) && Array.isArray(dashboard.views) ? dashboard.views : [];
  const byPath = views.findIndex((v) => isObject(v) && v.path === view);
  return byPath >= 0 ? byPath : Number(view || 0);
}

/** Whether this user can save the dashboard at `urlPath` from the card. A YAML-mode dashboard only changes in its file. */
export function canSave(hass: HomeAssistant, urlPath: string | null): boolean {
  return !!hass.callWS && !!hass.user?.is_admin && hass.panels?.[urlPath ?? "lovelace"]?.config?.mode !== "yaml";
}

/**
 * Replaces the card whose config is `old` with `next` in the dashboard at `urlPath` and saves it.
 * Throws SaveError with a message for the user when that can't be done safely.
 */
export async function saveCard(
  hass: HomeAssistant,
  urlPath: string | null,
  old: Record<string, unknown>,
  next: Record<string, unknown>,
  view = "",
): Promise<void> {
  if (!hass.callWS) throw new SaveError("This Home Assistant doesn't allow saving from the card.");
  let dashboard: unknown;
  try {
    dashboard = await hass.callWS({ type: "lovelace/config", url_path: urlPath });
  } catch (err) {
    throw new SaveError(`Couldn't read the dashboard: ${reason(err)}.`);
  }
  if (isObject(dashboard) && "strategy" in dashboard) {
    throw new SaveError("This dashboard is generated by Home Assistant, so there is no saved card to change.");
  }
  let paths = findCard(dashboard, old);
  if (paths.length > 1) {
    // The same card in a phone view and a tablet view, say. The one on screen is the one being edited.
    const shown = viewIndex(dashboard, view);
    const here = paths.filter((path) => path[0] === "views" && path[1] === shown);
    if (here.length > 0) paths = here;
  }
  if (paths.length === 0) {
    throw new SaveError("Couldn't find this card in the saved dashboard. It may have been changed in another tab, so reload the page to pick that up. A card made by a template or another card can't be saved from here.");
  }
  if (paths.length > 1) {
    throw new SaveError("The dashboard has more than one card with exactly this config, so it isn't clear which one to change.");
  }
  try {
    await hass.callWS({ type: "lovelace/config/save", url_path: urlPath, config: replaceAt(dashboard, paths[0], next) });
  } catch (err) {
    throw new SaveError(`Home Assistant didn't save the dashboard: ${reason(err)}.`);
  }
}
